import React, { useState } from 'react';
import { 
  Camera, Image as ImageIcon, Video, Upload, ChevronRight, ChevronLeft,
  MessageSquare, CheckCircle, RefreshCcw, Loader2, Sparkles, 
  LayoutPanelLeft, Copy, Check, Volume2, 
  Settings, ToggleLeft, ToggleRight, Mic, ChevronDown, ChevronUp,
  ExternalLink, AlertCircle, Eye, Tag
} from 'lucide-react';

export default function App() {
  const [step, setStep] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFetchingSuggestions, setIsFetchingSuggestions] = useState(false);
  const [activeTab, setActiveTab] = useState(0);
  const [copiedStates, setCopiedStates] = useState({ image: false, video: false, voice: false });
  const [showMoreSettings, setShowMoreSettings] = useState(false);
  const [showMoreVibes, setShowMoreVibes] = useState(false);
  const [apiError, setApiError] = useState(null);
  const [generatedResults, setGeneratedResults] = useState([]);
  
  // Dynamic recommendations generated by Gemini AI during transition from step 1 to 2
  const [aiSuggestions, setAiSuggestions] = useState({
    settings: [],
    vibes: []
  });

  const [formData, setFormData] = useState({
    faceImage: null,
    category: '',
    productDetail: '',
    setting: '',
    vibe: '',
    useHook: true,
    usePlaceholder: false,
    visualStyle: 'Photorealistic',
    voiceStyle: 'Percakapan/Alami'
  });

  const categories = [
    'Fashion & Aksesoris',
    'Elektronik & Gadget',
    'Kecantikan & Perawatan Diri',
    'Rumah & Kehidupan',
    'Kesehatan & Kebugaran',
    'Baby & Toys',
    'Makanan & Minuman',
    'Olahraga & Luar Ruangan',
    'Buku & Hobi',
    'Otomotif'
  ];

  const visualStyles = [
    { name: 'Photorealistic', desc: 'Terlihat seperti foto asli dengan detail tekstur nyata.' },
    { name: 'Documentary', desc: 'Gaya jurnalistik, alami, tanpa rekayasa, sering kali candid.' },
    { name: 'Studio', desc: 'Bersih, tajam, dan bebas dari distraksi latar belakang.' },
    { name: 'Cinematic', desc: 'Terlihat seperti adegan film dengan komposisi dramatis.' }
  ];

  const voiceStyles = [
    { name: 'Percakapan/Alami', desc: 'Mudah dipahami & ramah, ideal untuk tutorial atau promosi santai.' },
    { name: 'Berwibawa/Profesional', desc: 'Tenang & kredibel, cocok untuk video korporasi atau edukasi mendalam.' },
    { name: 'Dramatis/Intens', desc: 'Penuh emosi & berwibawa, sering dipakai dalam trailer/konten narasi kuat.' },
    { name: 'Ceria/Energik', desc: 'Upbeat & menyenangkan, pas untuk konten harian berenergi tinggi.' },
    { name: 'IVR/Teknis', desc: 'Jelas & netral, terstruktur untuk panduan teknis yang mudah dimengerti.' }
  ];

  const handleNext = () => setStep(step + 1);
  const handleBack = () => setStep(step - 1);
  
  const handleReset = () => {
    setStep(1);
    setActiveTab(0);
    setCopiedStates({ image: false, video: false, voice: false });
    setShowMoreSettings(false);
    setShowMoreVibes(false);
    setApiError(null);
    setGeneratedResults([]);
    setAiSuggestions({ settings: [], vibes: [] });
    setFormData({
      faceImage: null,
      category: '',
      productDetail: '',
      setting: '',
      vibe: '',
      useHook: true,
      usePlaceholder: false,
      visualStyle: 'Photorealistic',
      voiceStyle: 'Percakapan/Alami'
    });
  };

  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const imageUrl = URL.createObjectURL(file);
      setFormData({ ...formData, faceImage: imageUrl });
    }
  };

  const handleRemoveImage = (e) => {
    e.preventDefault();
    setFormData({ ...formData, faceImage: null });
  };

  const handleCopyText = (text, type) => {
    const tempTextarea = document.createElement('textarea');
    tempTextarea.value = text;
    document.body.appendChild(tempTextarea);
    tempTextarea.select();
    try {
      document.execCommand('copy');
      setCopiedStates(prev => ({ ...prev, [type]: true }));
      setTimeout(() => {
        setCopiedStates(prev => ({ ...prev, [type]: false }));
      }, 2000);
    } catch (err) {
      console.error('Gagal menyalin teks', err);
    }
    document.body.removeChild(tempTextarea);
  };

  // REVISI LANGKAH 1 -> 2: PROSES GEMINI AI UNTUK MERANCANG LATAR BELAKANG & SUASANA SECARA DINAMIS
  const handleTransitionToStep2 = async () => {
    setIsFetchingSuggestions(true);
    setApiError(null);

    const apiKey = "";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;

    const systemPrompt = `You are an expert creative director specializing in high-conversion ad campaign conceptualization.
Your goal is to generate exactly 8 highly creative setting locations and exactly 8 marketing-oriented vibes/moods tailored precisely to the user's product and category.
All outputs must be written in Indonesian. Keep each suggestions short and catchy (typically 2 to 4 words). Do not return markdown, strictly output the specified JSON format.`;

    const userPrompt = `Rancang usulan ide untuk produk berikut:
Kategori Produk: ${formData.category}
Detail Spesifik Produk: ${formData.productDetail}

Format pengeluaran JSON harus memiliki:
1. "settings": Array yang berisikan persis 8 ide latar belakang/lokasi syuting yang relevan dan estetik.
2. "vibes": Array yang berisikan persis 8 ide suasana/mood/tonalitas iklan yang memikat calon pembeli.`;

    const responseSchema = {
      type: "OBJECT",
      properties: {
        settings: {
          type: "ARRAY",
          items: { type: "STRING" },
          description: "8 dynamic background settings specifically for this product"
        },
        vibes: {
          type: "ARRAY",
          items: { type: "STRING" },
          description: "8 dynamic marketing vibes specifically for this product"
        }
      },
      required: ["settings", "vibes"]
    };

    const payload = {
      contents: [{ parts: [{ text: userPrompt }] }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: responseSchema
      }
    };

    let success = false;
    let data = null;

    // Retry up to 3 times with basic delay
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload)
        });

        if (response.ok) {
          const jsonRes = await response.json();
          const textResponse = jsonRes.candidates?.[0]?.content?.parts?.[0]?.text;
          if (textResponse) {
            data = JSON.parse(textResponse);
            success = true;
            break;
          }
        }
      } catch (err) {
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    if (success && data && data.settings && data.vibes) {
      setAiSuggestions(data);
      setStep(2);
    } else {
      // Fallback suggestions if API fails to prevent blocking user journey
      setAiSuggestions({
        settings: [
          'Studio Minimalis Putih', 'Kafe Estetik Modern', 'Ruang Tamu Cozy', 'Jalanan Kota Tropis',
          'Taman Terbuka Hijau', 'Meja Kerja Minimalis', 'Teras Rumah Hangat', 'Studio Cahaya Alami'
        ],
        vibes: [
          'Cinematic & Dramatis', 'Edgy & Bold', 'Fun & Ceria', 'Elegan & Mewah',
          'Casual & Santai', 'Estetik & Minimalis', 'Retro & Vintage', 'Modern & Profesional'
        ]
      });
      setStep(2);
    }
    setIsFetchingSuggestions(false);
  };

  // REVISI OUTPUT PROMPT: GEMINI AI MENGHASILKAN PROMPT YANG JAUH LEBIH DETIL, RIGID, DAN DESKRIPTIF
  const generatePromptsWithGemini = async () => {
    setIsGenerating(true);
    setApiError(null);

    const apiKey = "";
    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;

    const systemPrompt = `You are a world-class AI Advertising Director, Cinematic DP, and veteran Copywriter. 
Your goal is to output an extremely detailed, 5-scene continuous storyboard sequence for a 30-second high-converting affiliate promo video based on user inputs.
The narrative MUST be incredibly cohesive from Scene 1 to Scene 5:
- Scene 1: Hook Pembuka (0-3s) - Grabs immediate attention with an intense/engaging hook or emotional pain point.
- Scene 2: Sorotan Estetika (3-8s) - Focuses heavily on the product's premium physical details, quality materials, and macro texture.
- Scene 3: Demonstrasi Aksi (8-15s) - Shows active and high-utility real-world usage/demo of the product.
- Scene 4: Transformasi Kepuasan (15-22s) - Highlights the emotional shift, delight, confidence, and positive payoff of using it.
- Scene 5: Call to Action (22-30s) - Clear persuasive outro pushing viewers to click the yellow cart or link.

CRITICAL INSTRUCTIONS FOR PROMPT DEPTH (To avoid any AI generator ambiguity):
1. "imagePrompt": Must be a hyper-detailed, highly descriptive, professional-grade prompt written in English (min 60-80 words). Incorporate specific cinematic camera settings (e.g., "shot on ARRI Alexa LF, 85mm anamorphic lens, shallow depth of field, f/1.4, volumetric warm studio light, high-end commercial color grading, sharp micro-textures of [product details], photorealistic, 8k resolution"). Respect the selected visual style: ${formData.visualStyle}.
2. "videoPrompt": Must be an incredibly vivid action prompt in English (min 60-80 words). Describe dynamic camera movements (e.g., "slow glide tracking gimbal shot, smooth rack focus from background to [product], extreme close-up panning at 60fps slow motion, realistic wind and particle simulations, seamless physical cloth/material physics, cinematic light leaks").
3. "voicePrompt": Must be an expressive, high-impact Indonesian Voiceover script. Include detailed vocal tone direction, speed of speech, emotional cue tags (e.g., "[pause 1s]", "[dengan nada berbisik penuh kekaguman]", "[intonasi ceria dan bersemangat]"), and ambient background sound effect directions (e.g., "[SFX: Suara langkah kaki lembut]", "[SFX: Gemerisik kemasan dibuka]").

Return the entire response strictly in the specified JSON format.`;

    const faceRefInstruction = formData.faceImage 
      ? `Indonesian model matching the provided reference face image, with consistent facial bone structure, hairstyle, and skin tone` 
      : `an attractive Indonesian protagonist model`;

    const placeholderInstruction = formData.usePlaceholder 
      ? `Use '[PROTAGONIST_MODEL]' to represent the model in both imagePrompt and videoPrompt for easy Face-Swap/ cref workflow. Description of the protagonist model: ${faceRefInstruction}.`
      : `Describe the model directly as: ${faceRefInstruction}.`;

    const userPrompt = `Rancang storyboard 5-scene yang bersinergi untuk produk ini:
Kategori: ${formData.category}
Detail Spesifik Produk: ${formData.productDetail}
Latar Tempat (Setting): ${formData.setting}
Atmosfer/Vibe: ${formData.vibe}
Gunakan Hook Emosional di Awal: ${formData.useHook ? "YA (buat intro yang memicu rasa ingin tahu)" : "TIDAK (langsung perkenalkan produk)"}
Gaya Visual Target: ${formData.visualStyle}
Gaya Voiceover Target: ${formData.voiceStyle}
Gaya Penulisan Model: ${placeholderInstruction}

Berikan output JSON terstruktur yang berisi array "scenes" dengan persis 5 elemen berurutan logis.`;

    const responseSchema = {
      type: "OBJECT",
      properties: {
        scenes: {
          type: "ARRAY",
          description: "An array of exactly 5 sequential scenes forming a coherent 30-second promotional video storyboard.",
          items: {
            type: "OBJECT",
            properties: {
              seq: { type: "STRING", description: "Scene identifier (e.g. Scene 1: Hook Pembuka)" },
              name: { type: "STRING", description: "Creative scene name" },
              description: { type: "STRING", description: "Detailed narrative action explanation in Indonesian" },
              imagePrompt: { type: "STRING", description: "Extremely long, hyper-detailed Midjourney/DALL-E 3 image prompt in English" },
              videoPrompt: { type: "STRING", description: "Extremely long, hyper-detailed Sora/Runway/Kling video action prompt in English" },
              voicePrompt: { type: "STRING", description: "Professional Indonesian voiceover script with tone markers and SFX cues" }
            },
            required: ["seq", "name", "description", "imagePrompt", "videoPrompt", "voicePrompt"]
          }
        }
      },
      required: ["scenes"]
    };

    const payload = {
      contents: [{ parts: [{ text: userPrompt }] }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: responseSchema
      }
    };

    const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

    let lastError = null;
    let success = false;
    let data = null;

    for (let attempt = 0; attempt < 5; attempt++) {
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload)
        });

        if (response.ok) {
          const jsonRes = await response.json();
          const textResponse = jsonRes.candidates?.[0]?.content?.parts?.[0]?.text;
          if (textResponse) {
            data = JSON.parse(textResponse);
            success = true;
            break;
          }
        } else {
          throw new Error(`Server merespons dengan status ${response.status}`);
        }
      } catch (err) {
        lastError = err;
        const backoffTime = Math.pow(2, attempt) * 1000;
        await delay(backoffTime);
      }
    }

    if (success && data && data.scenes) {
      setGeneratedResults(data.scenes);
      setStep(4);
    } else {
      setApiError(lastError ? lastError.message : "Gagal memproses dengan Gemini AI. Silakan periksa jaringan Anda atau coba sesaat lagi.");
    }
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-sans p-4 md:p-8 pb-20">
      <div className="max-w-5xl mx-auto">
        
        {/* Header */}
        <header className="mb-8 text-center animate-in fade-in duration-300">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-xs font-bold mb-4">
            <Sparkles className="w-3.5 h-3.5 animate-pulse" /> Live Gemini 2.5 AI Processor
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 flex items-center justify-center gap-2 mb-2 tracking-tight">
            Affiliate Prompt Generator
          </h1>
          <p className="text-slate-500 max-w-md mx-auto text-sm md:text-base">
            Sistem Pintar Pembuat Prompt Kreatif Berurutan Khusus Foto, Video & Suara Menggunakan Pemrosesan Riil Gemini AI.
          </p>
        </header>

        {/* Progress Bar */}
        <div className="flex justify-between items-center mb-8 relative px-4 md:px-12 max-w-xl mx-auto">
          <div className="absolute left-6 right-6 top-1/2 -translate-y-1/2 h-1 bg-slate-200 -z-10 rounded"></div>
          <div 
            className="absolute left-6 top-1/2 -translate-y-1/2 h-1 bg-indigo-600 -z-10 rounded transition-all duration-500" 
            style={{ width: `${((step - 1) / 3) * 100}%` }}
          ></div>
          
          {[1, 2, 3, 4].map((num) => (
            <div 
              key={num} 
              className={`w-9 h-9 md:w-10 md:h-10 rounded-full flex flex-col items-center justify-center font-bold border-4 transition-all duration-300 relative ${
                step >= num 
                  ? 'bg-indigo-600 text-white border-indigo-200 shadow-md shadow-indigo-100 scale-105' 
                  : 'bg-slate-100 text-slate-400 border-white'
              }`}
            >
              <span className="text-sm">{num}</span>
              <span className="absolute -bottom-6 text-[9px] font-bold tracking-wider text-slate-400 whitespace-nowrap hidden sm:block">
                {num === 1 && "Produk"}
                {num === 2 && "Klarifikasi"}
                {num === 3 && "Strategi"}
                {num === 4 && "Hasil"}
              </span>
            </div>
          ))}
        </div>

        {apiError && (
          <div className="bg-red-50 border border-red-200 text-red-800 p-4 rounded-xl mb-6 flex items-start gap-3 max-w-2xl mx-auto animate-in fade-in duration-300">
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
            <div>
              <h4 className="font-bold text-sm">Terjadi Masalah Koneksi</h4>
              <p className="text-xs text-red-700 mt-1">{apiError}</p>
              <button 
                onClick={generatePromptsWithGemini}
                className="mt-3 px-3 py-1.5 bg-red-600 text-white rounded-lg text-xs font-bold hover:bg-red-700 transition-colors flex items-center gap-1"
              >
                <RefreshCcw className="w-3 h-3" /> Coba Hubungkan Kembali
              </button>
            </div>
          </div>
        )}

        <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-100 transition-all duration-300 mt-8">
          
          {/* STEP 1: INPUT DATA */}
          {step === 1 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <Upload className="w-5 h-5 text-indigo-600" />
                Langkah 1: Input Dasar Produk
              </h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Upload Area */}
                <label className="border-2 border-dashed border-slate-300 rounded-xl p-8 flex flex-col items-center justify-center text-center hover:border-indigo-400 transition-all cursor-pointer bg-slate-50 relative overflow-hidden group min-h-[220px]">
                  <input 
                    type="file" 
                    accept="image/png, image/jpeg, image/webp" 
                    className="hidden" 
                    onChange={handleImageUpload}
                  />
                  
                  {formData.faceImage ? (
                    <>
                      <img 
                        src={formData.faceImage} 
                        alt="Preview Wajah" 
                        className="absolute inset-0 w-full h-full object-cover opacity-40 group-hover:opacity-20 transition-opacity" 
                      />
                      <div className="relative z-10 flex flex-col items-center">
                        <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4 shadow-sm animate-bounce">
                          <CheckCircle className="w-8 h-8 text-green-600" />
                        </div>
                        <h3 className="font-semibold mb-1 text-slate-900">Gambar Wajah Terpilih</h3>
                        <p className="text-xs text-slate-600 mb-4 bg-white/90 px-2 py-1 rounded">Model referensi wajah aktif</p>
                        <button 
                          onClick={handleRemoveImage}
                          className="px-4 py-2 bg-white border border-red-200 text-red-600 rounded-lg text-xs font-semibold hover:bg-red-50 transition-colors shadow-sm"
                        >
                          Hapus / Ganti
                        </button>
                      </div>
                    </>
                  ) : (
                    <>
                      <div className="w-14 h-14 bg-indigo-100 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                        <ImageIcon className="w-7 h-7 text-indigo-600" />
                      </div>
                      <h3 className="font-bold text-slate-800 mb-1">Unggah Wajah Model</h3>
                      <p className="text-xs text-slate-500 mb-4 max-w-[200px]">Opsional: Unggah foto wajah model utama Anda untuk dianalisis oleh instruksi prompt AI</p>
                      <div className="px-4 py-2 bg-white border border-slate-300 rounded-lg text-xs font-semibold hover:bg-slate-50 shadow-sm pointer-events-none">Pilih File</div>
                    </>
                  )}
                </label>

                {/* Form Inputs */}
                <div className="space-y-5">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Kategori Produk <span className="text-red-500">*</span></label>
                    <select 
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all bg-white text-sm"
                      value={formData.category}
                      onChange={(e) => setFormData({...formData, category: e.target.value, setting: '', vibe: ''})}
                    >
                      <option value="">-- Pilih Kategori --</option>
                      {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                    </select>
                  </div>
                  
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Detail Produk Spesifik <span className="text-red-500">*</span></label>
                    <input 
                      type="text" 
                      placeholder="Cth: Lipstik matte warna merah ceri, Sneakers putih rajut" 
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all text-sm"
                      value={formData.productDetail}
                      onChange={(e) => setFormData({...formData, productDetail: e.target.value})}
                    />
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
                <button 
                  onClick={handleTransitionToStep2}
                  disabled={!formData.category || !formData.productDetail || isFetchingSuggestions}
                  className="bg-indigo-600 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-lg shadow-indigo-100"
                >
                  {isFetchingSuggestions ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Menganalisis Konsep...
                    </>
                  ) : (
                    <>
                      Lanjut ke Penyesuaian <ChevronRight className="w-5 h-5" />
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* STEP 2: CLARIFICATION WITH DYNAMIC AI RECOMMENDATIONS */}
          {step === 2 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300 bg-slate-50">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <MessageSquare className="w-5 h-5 text-indigo-600" />
                Langkah 2: Klarifikasi AI (Rekomendasi dari Gemini)
              </h2>
              
              <div className="bg-white p-6 md:p-8 rounded-2xl border border-slate-200 shadow-sm mb-6 animate-in fade-in duration-300">
                <div className="flex gap-4 mb-6 pb-6 border-b border-slate-100">
                  <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center shrink-0">
                    <Sparkles className="w-5 h-5 text-indigo-600" />
                  </div>
                  <p className="text-slate-700 leading-relaxed text-sm md:text-base">
                    Gemini AI telah menganalisis produk <span className="font-bold text-indigo-600">{formData.productDetail}</span> untuk memformulasikan saran Latar & Suasana dengan konversi penjualan tertinggi!
                  </p>
                </div>
                
                <div className="space-y-8">
                  {/* Dynamic Setting Suggestions from Gemini */}
                  <div>
                    <label className="block text-sm font-bold text-slate-800 mb-3">1. Latar Belakang (Setting) Lokasi:</label>
                    <input 
                      type="text" 
                      placeholder="Pilih di bawah atau tulis kustom sendiri..." 
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none mb-3 bg-slate-50 text-sm"
                      value={formData.setting}
                      onChange={(e) => setFormData({...formData, setting: e.target.value})}
                    />
                    <div className="space-y-2">
                      <div className="flex flex-wrap gap-2">
                        {aiSuggestions.settings.slice(0, 4).map(sug => (
                          <button 
                            key={sug}
                            onClick={() => setFormData({...formData, setting: sug})}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all ${
                              formData.setting === sug 
                                ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' 
                                : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                            }`}
                          >
                            + {sug}
                          </button>
                        ))}

                        {showMoreSettings && aiSuggestions.settings.slice(4, 8).map(sug => (
                          <button 
                            key={sug}
                            onClick={() => setFormData({...formData, setting: sug})}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all animate-in fade-in zoom-in-95 duration-200 ${
                              formData.setting === sug 
                                ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' 
                                : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                            }`}
                          >
                            + {sug}
                          </button>
                        ))}
                      </div>

                      <button
                        onClick={() => setShowMoreSettings(!showMoreSettings)}
                        className="flex items-center gap-1 text-xs font-bold text-indigo-600 hover:text-indigo-800 mt-2 transition-colors focus:outline-none"
                      >
                        {showMoreSettings ? (
                          <><ChevronUp className="w-3.5 h-3.5" /> Sembunyikan rekomendasi lainnya</>
                        ) : (
                          <><ChevronDown className="w-3.5 h-3.5" /> Rekomendasi lainnya (Dihasilkan AI)</>
                        )}
                      </button>
                    </div>
                  </div>
                  
                  {/* Dynamic Vibe Suggestions from Gemini */}
                  <div>
                    <label className="block text-sm font-bold text-slate-800 mb-3">2. Suasana (Vibe & Mood) yang Diinginkan:</label>
                    <input 
                      type="text" 
                      placeholder="Pilih di bawah atau tulis kustom sendiri..." 
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none mb-3 bg-slate-50 text-sm"
                      value={formData.vibe}
                      onChange={(e) => setFormData({...formData, vibe: e.target.value})}
                    />
                    <div className="space-y-2">
                      <div className="flex flex-wrap gap-2">
                        {aiSuggestions.vibes.slice(0, 4).map(sug => (
                          <button 
                            key={sug}
                            onClick={() => setFormData({...formData, vibe: sug})}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all ${
                              formData.vibe === sug 
                                ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' 
                                : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                            }`}
                          >
                            + {sug}
                          </button>
                        ))}

                        {showMoreVibes && aiSuggestions.vibes.slice(4, 8).map(sug => (
                          <button 
                            key={sug}
                            onClick={() => setFormData({...formData, vibe: sug})}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all animate-in fade-in zoom-in-95 duration-200 ${
                              formData.vibe === sug 
                                ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm' 
                                : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                            }`}
                          >
                            + {sug}
                          </button>
                        ))}
                      </div>

                      <button
                        onClick={() => setShowMoreVibes(!showMoreVibes)}
                        className="flex items-center gap-1 text-xs font-bold text-indigo-600 hover:text-indigo-800 mt-2 transition-colors focus:outline-none"
                      >
                        {showMoreVibes ? (
                          <><ChevronUp className="w-3.5 h-3.5" /> Sembunyikan rekomendasi lainnya</>
                        ) : (
                          <><ChevronDown className="w-3.5 h-3.5" /> Rekomendasi lainnya (Dihasilkan AI)</>
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex justify-between items-center mt-8">
                <button 
                  onClick={handleBack}
                  className="px-5 py-3 text-slate-600 font-bold hover:bg-slate-200 rounded-xl transition-colors text-sm"
                >
                  Kembali
                </button>
                <button 
                  onClick={handleNext}
                  disabled={!formData.setting || !formData.vibe}
                  className="bg-indigo-600 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 disabled:opacity-50 disabled:shadow-none text-sm"
                >
                  Atur Strategi Promosi <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: STRATEGIES STEP */}
          {step === 3 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <Settings className="w-5 h-5 text-indigo-600" />
                Langkah 3: Strategi & Gaya Promosi
              </h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-6">
                <div className="space-y-6">
                  <div className="p-5 bg-slate-50 border border-slate-100 rounded-xl">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h4 className="font-bold text-slate-800 text-sm">Gunakan Hook Menarik</h4>
                        <p className="text-xs text-slate-500 max-w-[280px]">AI suara akan membuat awal video memicu rasa ingin tahu audiens secara dramatis.</p>
                      </div>
                      <button 
                        onClick={() => setFormData({...formData, useHook: !formData.useHook})}
                        className="text-indigo-600 hover:scale-105 transition-transform focus:outline-none"
                      >
                        {formData.useHook ? (
                          <ToggleRight className="w-10 h-10 animate-in fade-in" />
                        ) : (
                          <ToggleLeft className="w-10 h-10 text-slate-400" />
                        )}
                      </button>
                    </div>
                    <div className="mt-3 bg-white px-3 py-2 rounded border border-slate-200/60 text-xs text-slate-600 italic">
                      {formData.useHook ? "Mulai dengan skenario emosional/pertanyaan pembuka" : "Mulai langsung membahas visual utama produk secara lugas"}
                    </div>
                  </div>

                  <div className="p-5 bg-slate-50 border border-slate-100 rounded-xl">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h4 className="font-bold text-slate-800 text-sm">Gunakan Placeholder Karakter</h4>
                        <p className="text-xs text-slate-500 max-w-[280px]">Menyisipkan tag khusus [PROTAGONIST_MODEL] untuk memudahkan workflow editing Face-Swap AI.</p>
                      </div>
                      <button 
                        onClick={() => setFormData({...formData, usePlaceholder: !formData.usePlaceholder})}
                        className="text-indigo-600 hover:scale-105 transition-transform focus:outline-none"
                      >
                        {formData.usePlaceholder ? (
                          <ToggleRight className="w-10 h-10 animate-in fade-in" />
                        ) : (
                          <ToggleLeft className="w-10 h-10 text-slate-400" />
                        )}
                      </button>
                    </div>
                    <div className="mt-3 bg-white px-3 py-2 rounded border border-slate-200/60 text-xs text-slate-600 italic">
                      {formData.usePlaceholder ? "Sangat disarankan untuk workflow Midjourney cref" : "Memakai model deskriptif umum"}
                    </div>
                  </div>
                </div>

                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-3">Gaya Visual (Tampilan AI):</label>
                    <div className="grid grid-cols-2 gap-3">
                      {visualStyles.map((style) => (
                        <button
                          key={style.name}
                          onClick={() => setFormData({...formData, visualStyle: style.name})}
                          className={`p-3 text-left rounded-xl border text-xs transition-all focus:outline-none ${
                            formData.visualStyle === style.name
                              ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                              : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                          }`}
                        >
                          <div className="font-bold mb-1">{style.name}</div>
                          <div className="text-[10px] text-slate-500 leading-tight">{style.desc}</div>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <div className="mt-6 pt-6 border-t border-slate-100">
                <label className="block text-sm font-bold text-slate-700 mb-3">Gaya Voiceover (Karakter & Tempo):</label>
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
                  {voiceStyles.map((voice) => (
                    <button
                      key={voice.name}
                      onClick={() => setFormData({...formData, voiceStyle: voice.name})}
                      className={`p-3 text-left rounded-xl border text-xs transition-all focus:outline-none ${
                        formData.voiceStyle === voice.name
                          ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                          : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                      }`}
                    >
                      <div className="font-bold mb-1 flex items-center gap-1 text-slate-800">
                        <Mic className="w-3.5 h-3.5 text-indigo-500" />
                        {voice.name}
                      </div>
                      <div className="text-[10px] text-slate-500 leading-tight">{voice.desc}</div>
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex justify-between items-center mt-8">
                <button 
                  onClick={handleBack}
                  disabled={isGenerating}
                  className="px-5 py-3 text-slate-600 font-bold hover:bg-slate-200 rounded-xl transition-colors text-sm"
                >
                  Kembali
                </button>
                <button 
                  onClick={generatePromptsWithGemini}
                  disabled={isGenerating}
                  className="bg-indigo-600 text-white px-6 md:px-8 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 text-sm"
                >
                  {isGenerating ? (
                    <><Loader2 className="w-4 h-4 animate-spin" /> Menganalisis Campaign dengan Gemini...</>
                  ) : (
                    <><Sparkles className="w-4 h-4 animate-bounce" /> Kirim ke Gemini AI</>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* STEP 4: RESULTS */}
          {step === 4 && generatedResults.length > 0 && (
            <div className="flex flex-col md:flex-row min-h-[620px] animate-in fade-in slide-in-from-bottom-4 duration-300">
              
              {/* Sidebar Storyboard */}
              <div className="w-full md:w-1/3 border-r border-slate-200 bg-slate-50 p-4 md:p-6 flex flex-col justify-between">
                <div>
                  <h3 className="font-bold flex items-center gap-2 mb-2 text-slate-800 text-sm md:text-base">
                    <LayoutPanelLeft className="w-5 h-5 text-indigo-600" />
                    Storyboard Aktif
                  </h3>
                  <p className="text-[11px] text-slate-500 mb-4 pb-4 border-b border-slate-200 leading-relaxed">
                    Setiap segmen di bawah dihasilkan secara real-time oleh Gemini AI. Berurutan harmonis dari Scene 1 s/d 5.
                  </p>
                  
                  <div className="space-y-3 max-h-[360px] md:max-h-none overflow-y-auto pr-1">
                    {generatedResults.map((result, idx) => (
                      <button 
                        key={idx}
                        onClick={() => {
                          setActiveTab(idx);
                          setCopiedStates({ image: false, video: false, voice: false });
                        }}
                        className={`w-full text-left p-3 rounded-xl border transition-all duration-200 focus:outline-none ${
                          activeTab === idx 
                          ? 'bg-indigo-600 text-white border-indigo-700 shadow-md transform scale-[1.01]' 
                          : 'bg-white border-slate-200 text-slate-700 hover:border-indigo-300'
                        }`}
                      >
                        <div className="flex justify-between items-center mb-1">
                          <span className={`text-[9px] font-extrabold px-1.5 py-0.5 rounded uppercase tracking-wider ${
                            activeTab === idx ? 'bg-indigo-700 text-indigo-100' : 'bg-slate-100 text-slate-500'
                          }`}>
                            Scene {idx + 1}
                          </span>
                          {activeTab === idx && <CheckCircle className="w-3.5 h-3.5" />}
                        </div>
                        <h4 className="font-bold text-xs mb-1 line-clamp-1">{result.name.replace(/^\d+\.\s*/, '')}</h4>
                        <p className={`text-[11px] line-clamp-2 ${activeTab === idx ? 'text-indigo-100' : 'text-slate-500'}`}>
                          {result.description}
                        </p>
                      </button>
                    ))}
                  </div>
                </div>
                
                <div className="mt-6 pt-6 border-t border-slate-200 space-y-2">
                   <button 
                     onClick={() => setStep(3)} 
                     className="w-full py-2.5 flex items-center justify-center gap-2 text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-xl hover:bg-indigo-100 transition-colors shadow-sm"
                   >
                    <ChevronLeft className="w-3.5 h-3.5" /> Sesuaikan Strategi
                  </button>
                   <button 
                     onClick={handleReset} 
                     className="w-full py-2.5 flex items-center justify-center gap-2 text-xs font-bold text-slate-600 bg-white border border-slate-300 rounded-xl hover:bg-slate-100 transition-colors shadow-sm"
                   >
                    <RefreshCcw className="w-3.5 h-3.5" /> Mulai Produk Baru
                  </button>
                </div>
              </div>

              {/* Main Prompt Display Area */}
              <div className="w-full md:w-2/3 p-6 md:p-8 bg-white flex flex-col justify-between">
                <div>
                  {/* REVISI POIN 3: BADGES KONFIGURASI PILIHAN USER */}
                  <div className="mb-6 bg-slate-50 border border-slate-100 rounded-xl p-4 animate-in fade-in duration-300">
                    <span className="text-[10px] font-extrabold text-slate-500 uppercase tracking-widest block mb-2.5 flex items-center gap-1.5">
                      <Tag className="w-3 h-3 text-indigo-500" /> Ringkasan Konfigurasi Kampanye
                    </span>
                    <div className="flex flex-wrap gap-2">
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        📦 {formData.category}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200 max-w-[200px] truncate" title={formData.productDetail}>
                        ✨ {formData.productDetail}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200 max-w-[150px] truncate" title={formData.setting}>
                        📍 Latar: {formData.setting}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200 max-w-[150px] truncate" title={formData.vibe}>
                        🎭 Vibe: {formData.vibe}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        👁️ Visual: {formData.visualStyle}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🎙️ Audio: {formData.voiceStyle}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🪝 Hook: {formData.useHook ? 'Aktif' : 'Non-Aktif'}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🖼️ Model: {formData.faceImage ? 'Referensi Wajah' : 'Umum'}
                      </span>
                      {formData.usePlaceholder && (
                        <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                          🏷️ Tag Placeholder Aktif
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b pb-4">
                    <div>
                      <span className="text-[10px] font-extrabold text-indigo-600 uppercase tracking-widest block mb-1">
                        {generatedResults[activeTab].seq}
                      </span>
                      <h2 className="text-xl md:text-2xl font-black text-slate-800 mb-2">{generatedResults[activeTab].name}</h2>
                    </div>
                  </div>

                  <div className="space-y-6">
                    {/* Image Prompt */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-indigo-700 font-bold text-sm">
                          <ImageIcon className="w-4 h-4" />
                          <span>Prompt Gambar (Lebih Detail & Deskriptif)</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a 
                            href="https://www.midjourney.com" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-indigo-100 hover:bg-indigo-200 text-indigo-700 px-2 py-0.5 rounded font-bold transition-all border border-indigo-200 flex items-center gap-0.5"
                          >
                            Midjourney <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a 
                            href="https://chat.openai.com" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-indigo-100 hover:bg-indigo-200 text-indigo-700 px-2 py-0.5 rounded font-bold transition-all border border-indigo-200 flex items-center gap-0.5"
                          >
                            DALL-E 3 <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea 
                          readOnly 
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-indigo-400 transition-colors leading-relaxed font-mono"
                          value={generatedResults[activeTab].imagePrompt}
                        />
                        <button 
                          onClick={() => handleCopyText(generatedResults[activeTab].imagePrompt, 'image')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${
                            copiedStates.image 
                              ? 'bg-green-600 text-white hover:bg-green-700' 
                              : 'bg-indigo-50 hover:bg-indigo-100 text-indigo-600'
                          }`}
                        >
                          {copiedStates.image ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin Prompt</>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Video Prompt */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-blue-700 font-bold text-sm">
                          <Video className="w-4 h-4" />
                          <span>Prompt Video Singkat (Lebih Detail & Deskriptif)</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a 
                            href="https://openai.com/sora" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Sora <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a 
                            href="https://runwayml.com" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Runway <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a 
                            href="https://klingai.com" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Kling AI <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea 
                          readOnly 
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-blue-400 transition-colors leading-relaxed font-mono"
                          value={generatedResults[activeTab].videoPrompt}
                        />
                        <button 
                          onClick={() => handleCopyText(generatedResults[activeTab].videoPrompt, 'video')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${
                            copiedStates.video 
                              ? 'bg-green-600 text-white hover:bg-green-700' 
                              : 'bg-blue-50 hover:bg-blue-100 text-blue-600'
                          }`}
                        >
                          {copiedStates.video ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin Prompt</>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Voice Prompt & Script */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm">
                          <Volume2 className="w-4 h-4" />
                          <span>Prompt Suara, Naskah & Panduan Audio</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a 
                            href="https://elevenlabs.io" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-emerald-100 hover:bg-emerald-200 text-emerald-700 px-2 py-0.5 rounded font-bold transition-all border border-emerald-200 flex items-center gap-0.5"
                          >
                            ElevenLabs <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a 
                            href="https://lovo.ai" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            className="bg-emerald-100 hover:bg-emerald-200 text-emerald-700 px-2 py-0.5 rounded font-bold transition-all border border-emerald-200 flex items-center gap-0.5"
                          >
                            Lovo AI <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea 
                          readOnly 
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-emerald-400 transition-colors leading-relaxed"
                          value={generatedResults[activeTab].voicePrompt}
                        />
                        <button 
                          onClick={() => handleCopyText(generatedResults[activeTab].voicePrompt, 'voice')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${
                            copiedStates.voice 
                              ? 'bg-green-600 text-white hover:bg-green-700' 
                              : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-600'
                          }`}
                        >
                          {copiedStates.voice ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin Prompt</>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-8 p-4 bg-amber-50 border border-amber-200 rounded-xl flex items-start gap-2.5 animate-pulse">
                  <span className="text-amber-500 font-bold text-xs shrink-0 mt-0.5">🎬 Tips Sinergi Storyboard:</span>
                  <p className="text-[11px] text-amber-800 leading-relaxed">
                    Setiap naskah scene di atas didesain **bersambung** membentuk jalan cerita iklan yang utuh. Bacakan atau buat audio secara berurutan (Scene 1 s/d Scene 5) untuk digabungkan menjadi satu video promosi utuh berdurasi 30 detik!
                  </p>
                </div>
              </div>

            </div>
          )}
          
        </div>
      </div>
    </div>
  );
}