import { useState, useEffect, ChangeEvent, MouseEvent } from 'react';
import {
  Image as ImageIcon, Video, Upload, ChevronRight, ChevronLeft,
  CheckCircle, RefreshCcw, Loader2, Sparkles,
  LayoutPanelLeft, Copy, Check, Volume2,
  Settings, ToggleLeft, ToggleRight, Mic, ChevronDown, ChevronUp,
  ExternalLink, AlertCircle, Tag, Key
} from 'lucide-react';

interface Scene {
  seq: string;
  name: string;
  description: string;
  imagePrompt: string;
  videoPrompt: string;
  voicePrompt: string;
}

interface UploadedFile {
  id: string;
  url: string;
  base64: string;
  mimeType: string;
}

interface AiSuggestions {
  settings: string[];
  vibes: string[];
}

interface FormData {
  category: string;
  productDetail: string;
  setting: string;
  vibe: string;
  useHook: boolean;
  usePlaceholder: boolean;
  useProductPlaceholder: boolean;
  visualStyle: string;
  voiceStyle: string;
  modelGender: string;
  voiceLanguage: string;
}

export default function App() {
  const [step, setStep] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFetchingSuggestions, setIsFetchingSuggestions] = useState(false);
  const [activeTab, setActiveTab] = useState(0);
  const [copiedStates, setCopiedStates] = useState({ image: false, video: false, voice: false });
  const [showMoreSettings, setShowMoreSettings] = useState(false);
  const [showMoreVibes, setShowMoreVibes] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);
  const [generatedResults, setGeneratedResults] = useState<Scene[]>([]);

  const [apiKey, setApiKey] = useState(() => localStorage.getItem('gemini_api_key') || '');
  const [modelName, setModelName] = useState(() => localStorage.getItem('gemini_model_name') || 'gemini-1.5-flash');
  const [apiKeyStatus, setApiKeyStatus] = useState<'idle' | 'validating' | 'valid' | 'invalid'>('idle');
  const [validationError, setValidationError] = useState<string | null>(null);

  const validateApiKey = async (keyToValidate: string) => {
    if (!keyToValidate.trim()) {
      setApiKeyStatus('idle');
      setValidationError(null);
      return;
    }

    setApiKeyStatus('validating');
    setValidationError(null);

    const url = `https://generativelanguage.googleapis.com/v1beta/models?key=${keyToValidate}`;
    try {
      const response = await fetch(url);
      if (response.ok) {
        setApiKeyStatus('valid');
      } else {
        const errorData = await response.json().catch(() => ({}));
        const message = errorData.error?.message || `Server merespons dengan status ${response.status}`;
        setApiKeyStatus('invalid');
        setValidationError(message);
      }
    } catch (err) {
      setApiKeyStatus('invalid');
      setValidationError('Gagal menghubungi server Google Gemini API. Periksa koneksi internet Anda.');
    }
  };

  useEffect(() => {
    const savedKey = localStorage.getItem('gemini_api_key');
    if (savedKey) {
      validateApiKey(savedKey);
    }
  }, []);

  const handleApiKeyChange = (key: string) => {
    setApiKey(key);
    localStorage.setItem('gemini_api_key', key);
    if (apiKeyStatus !== 'idle') {
      setApiKeyStatus('idle');
    }
  };

  const handleModelChange = (model: string) => {
    setModelName(model);
    localStorage.setItem('gemini_model_name', model);
  };

  // Dynamic recommendations generated by Gemini AI during transition from step 1 to 2
  const [aiSuggestions, setAiSuggestions] = useState<AiSuggestions>({
    settings: [],
    vibes: []
  });

  const [productImages, setProductImages] = useState<UploadedFile[]>([]);
  const [modelImages, setModelImages] = useState<UploadedFile[]>([]);

  const [formData, setFormData] = useState<FormData>({
    category: '',
    productDetail: '',
    setting: '',
    vibe: '',
    useHook: true,
    usePlaceholder: false,
    useProductPlaceholder: false,
    visualStyle: 'Photorealistic',
    voiceStyle: 'Percakapan/Alami',
    modelGender: 'Bebas',
    voiceLanguage: 'Bahasa Indonesia'
  });

  const categories = [
    'Fashion & Aksesoris',
    'Elektronik & Gadget',
    'Kecantikan & Perawatan Diri',
    'Rumah & Kehidupan',
    'Kesehatan & Kebugaran',
    'Baby & Toys',
    'Makanan & Minuman',
    'Olahraga & Luar Ruangan',
    'Buku & Hobi',
    'Otomotif'
  ];

  const visualStyles = [
    { name: 'Photorealistic', desc: 'Terlihat seperti foto asli dengan detail tekstur nyata.' },
    { name: 'Documentary', desc: 'Gaya jurnalistik, alami, tanpa rekayasa, sering kali candid.' },
    { name: 'Studio', desc: 'Bersih, tajam, dan bebas dari distraksi latar belakang.' },
    { name: 'Cinematic', desc: 'Terlihat seperti adegan film dengan komposisi dramatis.' }
  ];

  const voiceStyles = [
    { name: 'Percakapan/Alami', desc: 'Mudah dipahami & ramah, ideal untuk tutorial atau promosi santai.' },
    { name: 'Berwibawa/Profesional', desc: 'Tenang & kredibel, cocok untuk video korporasi atau edukasi mendalam.' },
    { name: 'Dramatis/Intens', desc: 'Penuh emosi & berwibawa, sering dipakai dalam trailer/konten narasi kuat.' },
    { name: 'Ceria/Energik', desc: 'Upbeat & menyenangkan, pas untuk konten harian berenergi tinggi.' },
    { name: 'IVR/Teknis', desc: 'Jelas & netral, terstruktur untuk panduan teknis yang mudah dimengerti.' }
  ];

  const handleNext = () => setStep(step + 1);
  const handleBack = () => setStep(step - 1);

  const handleReset = () => {
    setStep(1);
    setActiveTab(0);
    setCopiedStates({ image: false, video: false, voice: false });
    setShowMoreSettings(false);
    setShowMoreVibes(false);
    setApiError(null);
    setGeneratedResults([]);
    setAiSuggestions({ settings: [], vibes: [] });
    setProductImages([]);
    setModelImages([]);
    setFormData({
      category: '',
      productDetail: '',
      setting: '',
      vibe: '',
      useHook: true,
      usePlaceholder: false,
      useProductPlaceholder: false,
      visualStyle: 'Photorealistic',
      voiceStyle: 'Percakapan/Alami',
      modelGender: 'Bebas',
      voiceLanguage: 'Bahasa Indonesia'
    });
  };

  const handleImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      Array.from(files).forEach(file => {
        const imageUrl = URL.createObjectURL(file);
        const reader = new FileReader();
        reader.onloadend = () => {
          const base64String = reader.result as string;
          const commaIndex = base64String.indexOf(',');
          if (commaIndex !== -1) {
            const base64 = base64String.substring(commaIndex + 1);
            setProductImages(prev => [
              ...prev,
              {
                id: Math.random().toString(36).substring(2, 9),
                url: imageUrl,
                base64,
                mimeType: file.type
              }
            ]);
          }
        };
        reader.readAsDataURL(file);
      });
    }
  };

  const handleRemoveImage = (id: string, e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setProductImages(prev => prev.filter(img => img.id !== id));
  };

  const handleModelImageUpload = (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      Array.from(files).forEach(file => {
        const imageUrl = URL.createObjectURL(file);
        const reader = new FileReader();
        reader.onloadend = () => {
          const base64String = reader.result as string;
          const commaIndex = base64String.indexOf(',');
          if (commaIndex !== -1) {
            const base64 = base64String.substring(commaIndex + 1);
            setModelImages(prev => [
              ...prev,
              {
                id: Math.random().toString(36).substring(2, 9),
                url: imageUrl,
                base64,
                mimeType: file.type
              }
            ]);
          }
        };
        reader.readAsDataURL(file);
      });
    }
  };

  const handleRemoveModelImage = (id: string, e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setModelImages(prev => prev.filter(img => img.id !== id));
  };

  const handleCopyText = (text: string, type: 'image' | 'video' | 'voice') => {
    const tempTextarea = document.createElement('textarea');
    tempTextarea.value = text;
    document.body.appendChild(tempTextarea);
    tempTextarea.select();
    try {
      document.execCommand('copy');
      setCopiedStates(prev => ({ ...prev, [type]: true }));
      setTimeout(() => {
        setCopiedStates(prev => ({ ...prev, [type]: false }));
      }, 2000);
    } catch (err) {
      console.error('Gagal menyalin teks', err);
    }
    document.body.removeChild(tempTextarea);
  };

  // REVISI LANGKAH 1 -> 2: PROSES GEMINI AI UNTUK MERANCANG LATAR BELAKANG & SUASANA SECARA DINAMIS
  const handleTransitionToStep2 = async () => {
    setIsFetchingSuggestions(true);
    setApiError(null);

    if (!apiKey.trim()) {
      // Fallback suggestions if no API key is provided
      setAiSuggestions({
        settings: [
          'Studio Minimalis Putih', 'Kafe Estetik Modern', 'Ruang Tamu Cozy', 'Jalanan Kota Tropis',
          'Taman Terbuka Hijau', 'Meja Kerja Minimalis', 'Teras Rumah Hangat', 'Studio Cahaya Alami'
        ],
        vibes: [
          'Cinematic & Dramatis', 'Edgy & Bold', 'Fun & Ceria', 'Elegan & Mewah',
          'Casual & Santai', 'Estetik & Minimalis', 'Retro & Vintage', 'Modern & Profesional'
        ]
      });
      setStep(2);
      setIsFetchingSuggestions(false);
      return;
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    const systemPrompt = `Role: Creative Director. Goal: generate 8 ad settings & 8 vibes tailored to product/category. Output Indonesian. Catchy & short (2-4 words). No markdown. JSON output only.`;

    const userPrompt = `Analyze the attached ${productImages.length} product reference photos and information to output suggestions.
Category: ${formData.category}
Detail: ${formData.productDetail}
JSON output structure:
1. "settings": 8 background locations for product ad.
2. "vibes": 8 marketing vibes/moods.`;

    const responseSchema = {
      type: "OBJECT",
      properties: {
        settings: {
          type: "ARRAY",
          items: { type: "STRING" },
          description: "8 dynamic background settings specifically for this product"
        },
        vibes: {
          type: "ARRAY",
          items: { type: "STRING" },
          description: "8 dynamic marketing vibes specifically for this product"
        }
      },
      required: ["settings", "vibes"]
    };

    const parts: any[] = [{ text: userPrompt }];
    productImages.forEach(img => {
      parts.push({
        inlineData: {
          mimeType: img.mimeType,
          data: img.base64
        }
      });
    });

    const payload = {
      contents: [{ parts }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: responseSchema
      }
    };

    let success = false;
    let data: AiSuggestions | null = null;

    // Retry up to 3 times with basic delay
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload)
        });

        if (response.ok) {
          const jsonRes = await response.json();
          const textResponse = jsonRes.candidates?.[0]?.content?.parts?.[0]?.text;
          if (textResponse) {
            data = JSON.parse(textResponse) as AiSuggestions;
            success = true;
            break;
          }
        } else {
          throw new Error(`Server merespons dengan status ${response.status}`);
        }
      } catch (err) {
        await new Promise(r => setTimeout(r, 1000));
      }
    }

    if (success && data && data.settings && data.vibes) {
      setAiSuggestions(data);
      setStep(2);
    } else {
      // Fallback suggestions if API fails to prevent blocking user journey
      setAiSuggestions({
        settings: [
          'Studio Minimalis Putih', 'Kafe Estetik Modern', 'Ruang Tamu Cozy', 'Jalanan Kota Tropis',
          'Taman Terbuka Hijau', 'Meja Kerja Minimalis', 'Teras Rumah Hangat', 'Studio Cahaya Alami'
        ],
        vibes: [
          'Cinematic & Dramatis', 'Edgy & Bold', 'Fun & Ceria', 'Elegan & Mewah',
          'Casual & Santai', 'Estetik & Minimalis', 'Retro & Vintage', 'Modern & Profesional'
        ]
      });
      setStep(2);
    }
    setIsFetchingSuggestions(false);
  };

  // REVISI OUTPUT PROMPT: GEMINI AI MENGHASILKAN PROMPT YANG JAUH LEBIH DETIL, RIGID, DAN DESKRIPTIF
  const generatePromptsWithGemini = async () => {
    setIsGenerating(true);
    setApiError(null);

    const productText = formData.useProductPlaceholder ? '[PRODUCT_PLACEHOLDER]' : (formData.productDetail || 'produk ini');
    const genderTerm = formData.modelGender === 'Laki-laki' ? 'model pria' : formData.modelGender === 'Perempuan' ? 'model wanita' : 'model Indonesia';
    const modelText = formData.usePlaceholder ? '[PROTAGONIST_MODEL]' : genderTerm;

    if (!apiKey.trim()) {
      // Fallback mock storyboard if no API key is provided
      const mockScenes: Scene[] = [
        {
          seq: "Scene 1: Hook Pembuka",
          name: "Masalah & Daya Tarik",
          description: `${modelText} melihat ke kamera dengan ekspresi bingung atau frustrasi sebelum menemukan solusi lewat ${productText}.`,
          imagePrompt: `Extreme close-up shot of a young attractive Indonesian model looking frustrated, soft natural lighting, shallow depth of field, 85mm lens, f/1.8, commercial color grading, high detail.`,
          videoPrompt: `A slow tilt-up showing the ${modelText} sitting in a cozy modern cafe, rubbing their temples, then smiling as they look down at ${productText} on the wooden table. 4k resolution, cinematic motion, 60fps.`,
          voicePrompt: `[intonasi ceria dan santai] "Bosen nggak sih sama pilihan yang biasa-biasa aja? Kenalin nih solusi baru yang wajib kamu coba!"`
        },
        {
          seq: "Scene 2: Sorotan Estetika",
          name: "Detail Premium Produk",
          description: `Kamera melakukan zoom detail produk untuk menyoroti tekstur, kemasan premium, dan warna estetis dari ${productText}.`,
          imagePrompt: `Macro product photography of ${productText} placed on a clean marble surface, studio softbox lighting, volumetric reflections, sharp textures, photorealistic, 8k.`,
          videoPrompt: `Slow panning shot across the sleek curves and fine materials of ${productText}, highlighting the brand logo and pristine texture. Studio lighting, elegant dust particles floating in the light shaft.`,
          voicePrompt: `[nada berbisik penuh kekaguman] "Lihat deh detailnya... Desainnya elegan banget dan dibikin dari bahan premium pilihan."`
        },
        {
          seq: "Scene 3: Demonstrasi Aksi",
          name: "Penggunaan Secara Riil",
          description: `${modelText} menunjukkan kegunaan dan cara mengoperasikan/mengaplikasikan ${productText} dengan senyuman puas.`,
          imagePrompt: `Close-up shot of an Indonesian model's hands holding and using ${productText}, warm morning light, cinematic atmosphere, f/2.0, detailed skin texture.`,
          videoPrompt: `Over-the-shoulder tracking shot showing the ${modelText} demonstrating how to use ${productText} step-by-step. Smooth hand movements, natural lighting, clean background.`,
          voicePrompt: `[intonasi bersemangat] "Nggak cuma keren, cara pakainya juga gampang banget lho. Praktis dan langsung kelihatan hasilnya!"`
        },
        {
          seq: "Scene 4: Transformasi Kepuasan",
          name: "Hasil Akhir & Percaya Diri",
          description: `${modelText} menunjukkan rasa bahagia dan kepuasan penuh setelah menggunakan ${productText}, memancarkan aura positif.`,
          imagePrompt: `Portrait of a smiling Indonesian model looking confident and happy, holding ${productText}, sun flare background, outdoor tropical city street, volumetric lighting.`,
          videoPrompt: `Medium shot of the ${modelText} laughing and showing off the final look/result with ${productText}. Dynamic camera dolly movement, vibrant colors, cinematic color grading.`,
          voicePrompt: `[nada gembira] "Hasilnya bener-bener memuaskan! Bikin aku makin percaya diri seharian."`
        },
        {
          seq: "Scene 5: Call to Action",
          name: "Ajakan Klik Keranjang",
          description: `Layar menunjukkan visual akhir produk beserta teks ajakan bertindak (CTA) untuk membeli via keranjang kuning.`,
          imagePrompt: `Minimalist dynamic layout showing ${productText} with a clean soft pastel background, text overlay reading 'Beli Sekarang', f/2.8, professional ad campaign style.`,
          videoPrompt: `A final slow zoom-out of ${productText} beside the ${modelText} who points smilingly towards the screen. Volumetric warm studio light.`,
          voicePrompt: `[intonasi mengajak dan ceria] "Yuk, langsung klik keranjang kuning di bawah sekarang juga sebelum kehabisan ya!"`
        }
      ];

      // Artificially wait for a short moment to simulate generator loading
      await new Promise(resolve => setTimeout(resolve, 1500));
      setGeneratedResults(mockScenes);
      setStep(4);
      setIsGenerating(false);
      return;
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

    const systemPrompt = `Role: Expert Creative Director & Cinematic DP. Goal: Output a cohesive 5-scene JSON storyboard for a 30s affiliate promo video.
Scenes:
1. Hook Pembuka (0-3s): Attention-grabbing hook or emotional pain point.
2. Sorotan Estetika (3-8s): Product premium details and macro texture zoom.
3. Demonstrasi Aksi (8-15s): Active product usage/demo in real world.
4. Transformasi Kepuasan (15-22s): Positive emotional payoff and satisfaction.
5. Call to Action (22-30s): Outro driving clicks and yellow cart purchases.

CRITICAL: Output prompts MUST be highly detailed, descriptive, and rigid to avoid AI ambiguity:
- "imagePrompt": Hyper-detailed English prompt (minimum 60-80 words). Must specify camera setup (e.g. shot on ARRI Alexa LF, 85mm lens, f/1.4, volumetric warm studio light, commercial color grading, sharp textures, photorealistic, 8k resolution) and style: ${formData.visualStyle}.
- "videoPrompt": Extremely vivid, long action English prompt (minimum 60-80 words). Describe dynamic camera motions (e.g. slow glide tracking gimbal shot, smooth rack focus, panning at 60fps slow motion, realistic physics).
- "voicePrompt": Expressive voiceover script written strictly in the selected language: ${formData.voiceLanguage}. Must include tone tags (e.g. [nada ceria], [pause 1s]) and ambient SFX cues (e.g. [SFX: ...]).
No markdown. JSON only.`;

    const genderLabel = formData.modelGender === 'Laki-laki' ? 'male' : formData.modelGender === 'Perempuan' ? 'female' : 'unisex';
    const faceRefInstruction = modelImages.length > 0
      ? `an attractive Indonesian ${genderLabel} protagonist model matching the physical traits, hair, face and outfit shown in the ${modelImages.length} attached model reference images`
      : `an attractive Indonesian ${genderLabel} protagonist model`;

    const placeholderInstruction = formData.usePlaceholder
      ? `Use '[PROTAGONIST_MODEL]' in prompts. Ref: ${faceRefInstruction}.`
      : `Describe model as: ${faceRefInstruction}.`;

    const productRefInstruction = productImages.length > 0
      ? `product in the ${productImages.length} attached reference images (${formData.productDetail})`
      : `${formData.productDetail}`;

    const productPlaceholderInstruction = formData.useProductPlaceholder
      ? `Use '[PRODUCT_PLACEHOLDER]' in prompts. Ref: ${productRefInstruction}.`
      : `Describe product as: ${productRefInstruction}.`;

    const userPrompt = `Generate 5-scene storyboard:
Category: ${formData.category}
Product: ${formData.productDetail}
Setting: ${formData.setting}
Vibe: ${formData.vibe}
Hook: ${formData.useHook ? "YES" : "NO"}
Visual: ${formData.visualStyle}
Voice Style: ${formData.voiceStyle}
Voice Language: ${formData.voiceLanguage}
Model writing style: ${placeholderInstruction}
Product writing style: ${productPlaceholderInstruction}

Note: If product photos and/or model photos are attached, analyze all of them (there are ${productImages.length} product photos and ${modelImages.length} model photos) and incorporate their visual details (appearance, colors, style, features, angles) into the imagePrompt and videoPrompt scenes.`;

    const responseSchema = {
      type: "OBJECT",
      properties: {
        scenes: {
          type: "ARRAY",
          description: "An array of exactly 5 sequential scenes forming a coherent 30-second promotional video storyboard.",
          items: {
            type: "OBJECT",
            properties: {
              seq: { type: "STRING", description: "Scene identifier (e.g. Scene 1: Hook Pembuka)" },
              name: { type: "STRING", description: "Creative scene name" },
              description: { type: "STRING", description: "Detailed narrative action explanation in Indonesian" },
              imagePrompt: { type: "STRING", description: "Extremely long, hyper-detailed Midjourney/DALL-E 3 image prompt in English" },
              videoPrompt: { type: "STRING", description: "Extremely long, hyper-detailed Sora/Runway/Kling video action prompt in English" },
              voicePrompt: { type: "STRING", description: `Professional voiceover script written in ${formData.voiceLanguage} with tone markers and SFX cues` }
            },
            required: ["seq", "name", "description", "imagePrompt", "videoPrompt", "voicePrompt"]
          }
        }
      },
      required: ["scenes"]
    };

    const parts: any[] = [{ text: userPrompt }];
    productImages.forEach(img => {
      parts.push({
        inlineData: {
          mimeType: img.mimeType,
          data: img.base64
        }
      });
    });
    modelImages.forEach(img => {
      parts.push({
        inlineData: {
          mimeType: img.mimeType,
          data: img.base64
        }
      });
    });

    const payload = {
      contents: [{ parts }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: responseSchema
      }
    };

    const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

    let lastError: Error | null = null;
    let success = false;
    let data: { scenes: Scene[] } | null = null;

    for (let attempt = 0; attempt < 5; attempt++) {
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload)
        });

        if (response.ok) {
          const jsonRes = await response.json();
          const textResponse = jsonRes.candidates?.[0]?.content?.parts?.[0]?.text;
          if (textResponse) {
            data = JSON.parse(textResponse) as { scenes: Scene[] };
            success = true;
            break;
          }
        } else {
          throw new Error(`Server merespons dengan status ${response.status}`);
        }
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        const backoffTime = Math.pow(2, attempt) * 1000;
        await delay(backoffTime);
      }
    }

    if (success && data && data.scenes) {
      setGeneratedResults(data.scenes);
      setStep(4);
    } else {
      setApiError(lastError ? lastError.message : "Gagal memproses dengan Gemini AI. Silakan periksa jaringan Anda atau coba sesaat lagi.");
    }
    setIsGenerating(false);
  };

  const activeScene = generatedResults[activeTab];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-sans p-4 md:p-8 pb-20">
      <div className="max-w-5xl mx-auto">

        {/* Header */}
        <header className="mb-8 text-center animate-in fade-in duration-300">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-xs font-bold mb-4">
            <Sparkles className="w-3.5 h-3.5 animate-pulse" /> by Qwerwoty
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 flex items-center justify-center gap-2 mb-2 tracking-tight">
            Affiliate Prompt Generator
          </h1>
          <p className="text-slate-500 max-w-md mx-auto text-sm md:text-base">
            Pembuat Prompt Kreatif Foto, Video & Suara.
          </p>
        </header>

        {/* API Key Configuration */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-5 mb-6 max-w-3xl mx-auto animate-in fade-in duration-300">
          <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-4">
            <div className="flex items-center gap-3 text-slate-800 shrink-0">
              <div className="w-9 h-9 rounded-xl bg-indigo-50 flex items-center justify-center border border-indigo-100">
                <Key className="w-4 h-4 text-indigo-600" />
              </div>
              <div>
                <span className="text-xs font-bold block text-slate-800">Gemini API Key</span>
                <span className="text-[10px] text-slate-500 block">Hubungkan dengan model AI</span>
              </div>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 grow md:justify-end">
              <div className="relative w-full sm:max-w-xs">
                <input
                  type="password"
                  placeholder="Masukkan API Key..."
                  className="w-full pl-3 pr-20 py-2 border border-slate-300 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none text-xs bg-slate-50/50"
                  value={apiKey}
                  onChange={(e) => handleApiKeyChange(e.target.value)}
                />
                <button
                  onClick={() => validateApiKey(apiKey)}
                  disabled={apiKeyStatus === 'validating'}
                  className="absolute right-1 top-1/2 -translate-y-1/2 px-2.5 py-1 bg-indigo-600 hover:bg-indigo-700 text-white disabled:opacity-50 text-[10px] font-bold rounded-lg transition-colors shadow-sm"
                >
                  {apiKeyStatus === 'validating' ? 'Checking...' : 'Verifikasi'}
                </button>
              </div>
              <select
                className="w-full sm:w-48 px-3 py-2 border border-slate-300 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none text-xs bg-slate-50/50 font-bold text-slate-700"
                value={modelName}
                onChange={(e) => handleModelChange(e.target.value)}
              >
                <option value="gemini-1.5-flash">Gemini 1.5 Flash (Stabil)</option>
                <option value="gemini-2.0-flash">Gemini 2.0 Flash</option>
                <option value="gemini-2.5-flash">Gemini 2.5 Flash</option>
                <option value="gemini-1.5-pro">Gemini 1.5 Pro</option>
              </select>
            </div>
          </div>
          {apiKey ? (
            <div className="mt-3.5 pt-3.5 border-t border-slate-100 flex flex-col gap-1 text-xs">
              <div className="flex items-center gap-2">
                <span className="text-slate-500 font-medium">Status API Key:</span>
                {apiKeyStatus === 'idle' && (
                  <span className="text-slate-500 font-semibold flex items-center gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-400"></span>
                    Belum diverifikasi. Silakan klik Verifikasi.
                  </span>
                )}
                {apiKeyStatus === 'validating' && (
                  <span className="text-indigo-600 font-semibold flex items-center gap-1 animate-pulse">
                    <Loader2 className="w-3 h-3 animate-spin" />
                    Memverifikasi...
                  </span>
                )}
                {apiKeyStatus === 'valid' && (
                  <span className="text-emerald-600 font-semibold flex items-center gap-1">
                    <CheckCircle className="w-3.5 h-3.5 text-emerald-500" />
                    Valid & Siap Digunakan
                  </span>
                )}
                {apiKeyStatus === 'invalid' && (
                  <span className="text-rose-600 font-semibold flex items-center gap-1">
                    <AlertCircle className="w-3.5 h-3.5 text-rose-500" />
                    Tidak Valid / Error Koneksi
                  </span>
                )}
              </div>
              {apiKeyStatus === 'invalid' && validationError && (
                <p className="text-[10px] text-rose-500 mt-1.5 p-2.5 rounded-xl bg-rose-50 border border-rose-100 font-mono leading-normal">
                  Detail: {validationError}
                </p>
              )}
            </div>
          ) : (
            <p className="text-[10px] text-amber-600 mt-3 pt-3 border-t border-slate-100 font-medium leading-normal">
              <span className="inline-block mr-1">⚠️</span>Mode Preview: Masukkan API Key Anda di atas untuk menghubungkan AI. Dapatkan key gratis di <a href="https://aistudio.google.com/" target="_blank" rel="noopener noreferrer" className="underline hover:text-amber-800 font-bold transition-colors">Google AI Studio</a>.
            </p>
          )}
        </div>

        {/* Progress Bar */}
        <div className="flex justify-between items-center mb-10 relative px-6 md:px-16 max-w-3xl mx-auto">
          <div className="absolute left-8 right-8 top-1/2 -translate-y-1/2 h-1 bg-slate-200 -z-10 rounded"></div>
          <div
            className="absolute left-8 top-1/2 -translate-y-1/2 h-1 bg-indigo-600 -z-10 rounded transition-all duration-500"
            style={{ width: `${((step - 1) / 3) * 100}%` }}
          ></div>

          {[1, 2, 3, 4].map((num) => {
            const isCompleted = step > num;
            const isActive = step === num;
            return (
              <div
                key={num}
                className={`w-9 h-9 md:w-10 md:h-10 rounded-full flex flex-col items-center justify-center font-bold border-4 transition-all duration-300 relative ${isActive
                  ? 'bg-indigo-600 text-white border-indigo-200 shadow-lg shadow-indigo-200 scale-110 ring-2 ring-indigo-500/50 ring-offset-2'
                  : isCompleted
                    ? 'bg-emerald-600 text-white border-emerald-100'
                    : 'bg-slate-100 text-slate-400 border-white'
                  }`}
              >
                {isCompleted ? (
                  <CheckCircle className="w-4 h-4 text-white" />
                ) : (
                  <span className="text-sm">{num}</span>
                )}
                <span className={`absolute -bottom-6 text-[9px] font-extrabold tracking-wider whitespace-nowrap hidden sm:block uppercase transition-colors duration-300 ${isActive
                  ? 'text-indigo-600'
                  : isCompleted
                    ? 'text-emerald-600'
                    : 'text-slate-400'
                  }`}>
                  {num === 1 && "Produk"}
                  {num === 2 && "Model"}
                  {num === 3 && "Klarifikasi"}
                  {num === 4 && "Hasil"}
                </span>
              </div>
            );
          })}
        </div>

        {apiError && (
          <div className="bg-red-50 border border-red-200 text-red-800 p-4 rounded-xl mb-6 flex items-start gap-3 max-w-3xl mx-auto animate-in fade-in duration-300">
            <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
            <div>
              <h4 className="font-bold text-sm">Terjadi Masalah Koneksi</h4>
              <p className="text-xs text-red-700 mt-1">{apiError}</p>
              <button
                onClick={generatePromptsWithGemini}
                className="mt-3 px-3 py-1.5 bg-red-600 text-white rounded-lg text-xs font-bold hover:bg-red-700 transition-colors flex items-center gap-1"
              >
                <RefreshCcw className="w-3 h-3" /> Coba Hubungkan Kembali
              </button>
            </div>
          </div>
        )}

        <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-100 transition-all duration-300 mt-8">

          {/* STEP 1: INPUT DATA */}
          {step === 1 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <Upload className="w-5 h-5 text-indigo-600" />
                Langkah 1: Input Dasar Produk
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Upload Area for Product Photos */}
                <div className="space-y-4">
                  <label className="border-2 border-dashed border-slate-300 rounded-xl p-6 flex flex-col items-center justify-center text-center hover:border-indigo-400 transition-all cursor-pointer bg-slate-50 relative overflow-hidden group min-h-[140px]">
                    <input
                      type="file"
                      multiple
                      accept="image/png, image/jpeg, image/webp"
                      className="hidden"
                      onChange={handleImageUpload}
                    />
                    <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                      <ImageIcon className="w-5 h-5 text-indigo-600" />
                    </div>
                    <h3 className="font-bold text-slate-800 text-xs">Unggah Foto Produk</h3>
                    <p className="text-[10px] text-slate-500 mb-2 max-w-[200px]">Bisa upload lebih dari 1 foto. Semakin banyak referensi, hasil prompt akan semakin baik!</p>
                    <div className="px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[10px] font-semibold hover:bg-slate-50 shadow-sm pointer-events-none">Pilih File</div>
                  </label>

                  {productImages.length > 0 && (
                    <div>
                      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">File Terunggah ({productImages.length})</div>
                      <div className="grid grid-cols-4 gap-2">
                        {productImages.map((img) => (
                          <div key={img.id} className="relative group aspect-square rounded-lg overflow-hidden border border-slate-200 bg-slate-100">
                            <img src={img.url} alt="Preview" className="w-full h-full object-cover" />
                            <button
                              onClick={(e) => handleRemoveImage(img.id, e)}
                              className="absolute top-1 right-1 bg-red-600/90 text-white w-4 h-4 rounded-full flex items-center justify-center text-xs font-bold hover:bg-red-700 transition-colors shadow-sm"
                              type="button"
                              title="Hapus foto"
                            >
                              &times;
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

                {/* Form Inputs */}
                <div className="space-y-5">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Kategori Produk <span className="text-red-500">*</span></label>
                    <select
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all bg-white text-sm"
                      value={formData.category}
                      onChange={(e) => setFormData({ ...formData, category: e.target.value, setting: '', vibe: '' })}
                    >
                      <option value="">-- Pilih Kategori --</option>
                      {categories.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Detail Produk Spesifik <span className="text-red-500">*</span></label>
                    <input
                      type="text"
                      placeholder="Cth: Lipstik matte warna merah ceri, Sneakers putih rajut"
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none transition-all text-sm mb-4"
                      value={formData.productDetail}
                      onChange={(e) => setFormData({ ...formData, productDetail: e.target.value })}
                    />
                  </div>

                  <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50 flex items-center justify-between gap-4">
                    <div>
                      <h4 className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                        <Tag className="w-3.5 h-3.5 text-indigo-600" />
                        Gunakan Placeholder Produk
                      </h4>
                      <p className="text-[10px] text-slate-500 mt-1 leading-normal">
                        Menyisipkan tag khusus <code className="bg-slate-200/80 px-1 py-0.5 rounded font-mono text-[9px] font-bold text-slate-700">[PRODUCT_PLACEHOLDER]</code> untuk mempermudah workflow template siap pakai.
                      </p>
                    </div>
                    <button
                      onClick={() => setFormData({ ...formData, useProductPlaceholder: !formData.useProductPlaceholder })}
                      className="shrink-0 transition-colors"
                      type="button"
                    >
                      {formData.useProductPlaceholder ? (
                        <ToggleRight className="w-9 h-9 text-indigo-600" />
                      ) : (
                        <ToggleLeft className="w-9 h-9 text-slate-400" />
                      )}
                    </button>
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t border-slate-100 flex justify-end">
                <button
                  onClick={handleTransitionToStep2}
                  disabled={!formData.category || !formData.productDetail || isFetchingSuggestions}
                  className="bg-indigo-600 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors shadow-lg shadow-indigo-100"
                >
                  {isFetchingSuggestions ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Menganalisis...
                    </>
                  ) : (
                    <>
                      Lanjut<ChevronRight className="w-5 h-5" />
                    </>
                  )}
                </button>
              </div>
            </div>
          )}

          {/* STEP 2: INPUT MODEL & KARAKTER */}
          {step === 2 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <Upload className="w-5 h-5 text-indigo-600" />
                Langkah 2: Input Model & Karakter
              </h2>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Upload Area for Model Photos */}
                <div className="space-y-4">
                  <label className="border-2 border-dashed border-slate-300 rounded-xl p-6 flex flex-col items-center justify-center text-center hover:border-indigo-400 transition-all cursor-pointer bg-slate-50 relative overflow-hidden group min-h-[140px]">
                    <input
                      type="file"
                      multiple
                      accept="image/png, image/jpeg, image/webp"
                      className="hidden"
                      onChange={handleModelImageUpload}
                    />
                    <div className="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center mb-2 group-hover:scale-110 transition-transform">
                      <ImageIcon className="w-5 h-5 text-indigo-600" />
                    </div>
                    <h3 className="font-bold text-slate-800 text-xs">Unggah Foto Model</h3>
                    <p className="text-[10px] text-slate-500 mb-2 max-w-[200px]">Bisa upload lebih dari 1 foto. Semakin banyak referensi, hasil prompt akan semakin baik!</p>
                    <div className="px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-[10px] font-semibold hover:bg-slate-50 shadow-sm pointer-events-none">Pilih File</div>
                  </label>

                  {modelImages.length > 0 && (
                    <div>
                      <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">File Terunggah ({modelImages.length})</div>
                      <div className="grid grid-cols-4 gap-2">
                        {modelImages.map((img) => (
                          <div key={img.id} className="relative group aspect-square rounded-lg overflow-hidden border border-slate-200 bg-slate-100">
                            <img src={img.url} alt="Preview" className="w-full h-full object-cover" />
                            <button
                              onClick={(e) => handleRemoveModelImage(img.id, e)}
                              className="absolute top-1 right-1 bg-red-600/90 text-white w-4 h-4 rounded-full flex items-center justify-center text-xs font-bold hover:bg-red-700 transition-colors shadow-sm"
                              type="button"
                              title="Hapus foto"
                            >
                              &times;
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

                {/* Form Inputs for Model */}
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2">Jenis Kelamin Model</label>
                    <div className="grid grid-cols-3 gap-3">
                      {['Bebas', 'Laki-laki', 'Perempuan'].map(gender => (
                        <button
                          key={gender}
                          type="button"
                          onClick={() => setFormData({ ...formData, modelGender: gender })}
                          className={`p-3 text-center rounded-xl border text-xs font-bold transition-all focus:outline-none ${formData.modelGender === gender
                            ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                            : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                            }`}
                        >
                          {gender}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Gunakan Placeholder Karakter */}
                  <div className="border border-slate-200 rounded-xl p-4 bg-slate-50/50 flex items-center justify-between gap-4">
                    <div>
                      <h4 className="text-xs font-bold text-slate-800 flex items-center gap-1.5">
                        <Tag className="w-3.5 h-3.5 text-indigo-600" />
                        Gunakan Placeholder Karakter
                      </h4>
                      <p className="text-[10px] text-slate-500 mt-1 leading-normal">
                        Menyisipkan tag khusus <code className="bg-slate-200/80 px-1 py-0.5 rounded font-mono text-[9px] font-bold text-slate-700">[PROTAGONIST_MODEL]</code> untuk memudahkan workflow Face-Swap.
                      </p>
                    </div>
                    <button
                      onClick={() => setFormData({ ...formData, usePlaceholder: !formData.usePlaceholder })}
                      className="shrink-0 transition-colors"
                      type="button"
                    >
                      {formData.usePlaceholder ? (
                        <ToggleRight className="w-9 h-9 text-indigo-600" />
                      ) : (
                        <ToggleLeft className="w-9 h-9 text-slate-400" />
                      )}
                    </button>
                  </div>
                </div>
              </div>

              <div className="flex justify-between items-center mt-8">
                <button
                  onClick={handleBack}
                  className="px-5 py-3 text-slate-600 font-bold hover:bg-slate-200 rounded-xl transition-colors text-sm"
                >
                  Kembali
                </button>
                <button
                  onClick={handleNext}
                  className="bg-indigo-600 text-white px-6 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 text-sm"
                >
                  Lanjut ke Klarifikasi <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: CLARIFICATION & STRATEGY */}
          {step === 3 && (
            <div className="p-6 md:p-8 animate-in fade-in slide-in-from-bottom-4 duration-300">
              <h2 className="text-xl font-bold mb-6 flex items-center gap-2 text-slate-800">
                <Settings className="w-5 h-5 text-indigo-600" />
                Langkah 3: Klarifikasi & Strategi Promosi
              </h2>

              <div className="bg-slate-50 p-5 rounded-2xl border border-slate-200 mb-8">
                <div className="flex gap-4">
                  <div className="w-9 h-9 bg-indigo-100 rounded-full flex items-center justify-center shrink-0">
                    <Sparkles className="w-4 h-4 text-indigo-600" />
                  </div>
                  <p className="text-xs text-slate-700 leading-relaxed">
                    Berdasarkan produk <span className="font-bold text-indigo-600">{formData.productDetail}</span> dan model yang diinput, tentukan setting latar belakang, suasana, visual, dan voiceover di bawah ini.
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-6">
                <div className="space-y-6">
                  {/* Setting selection */}
                  <div>
                    <label className="block text-sm font-bold text-slate-800 mb-2">Latar Belakang (Setting) Lokasi:</label>
                    <input
                      type="text"
                      placeholder="Pilih di bawah atau tulis kustom sendiri..."
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none mb-3 bg-slate-50 text-sm"
                      value={formData.setting}
                      onChange={(e) => setFormData({ ...formData, setting: e.target.value })}
                    />
                    <div className="space-y-2">
                      <div className="flex flex-wrap gap-2">
                        {aiSuggestions.settings.slice(0, 4).map(sug => (
                          <button
                            key={sug}
                            type="button"
                            onClick={() => setFormData({ ...formData, setting: sug })}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all ${formData.setting === sug
                              ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm'
                              : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                              }`}
                          >
                            + {sug}
                          </button>
                        ))}

                        {showMoreSettings && aiSuggestions.settings.slice(4, 8).map(sug => (
                          <button
                            key={sug}
                            type="button"
                            onClick={() => setFormData({ ...formData, setting: sug })}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all animate-in fade-in zoom-in-95 duration-200 ${formData.setting === sug
                              ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm'
                              : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                              }`}
                          >
                            + {sug}
                          </button>
                        ))}
                      </div>

                      <button
                        type="button"
                        onClick={() => setShowMoreSettings(!showMoreSettings)}
                        className="flex items-center gap-1 text-xs font-bold text-indigo-600 hover:text-indigo-800 mt-2 transition-colors focus:outline-none"
                      >
                        {showMoreSettings ? (
                          <><ChevronUp className="w-3.5 h-3.5" /> Sembunyikan</>
                        ) : (
                          <><ChevronDown className="w-3.5 h-3.5" /> Rekomendasi lainnya</>
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Vibe selection */}
                  <div>
                    <label className="block text-sm font-bold text-slate-800 mb-2">Suasana (Vibe & Mood):</label>
                    <input
                      type="text"
                      placeholder="Pilih di bawah atau tulis kustom sendiri..."
                      className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none mb-3 bg-slate-50 text-sm"
                      value={formData.vibe}
                      onChange={(e) => setFormData({ ...formData, vibe: e.target.value })}
                    />
                    <div className="space-y-2">
                      <div className="flex flex-wrap gap-2">
                        {aiSuggestions.vibes.slice(0, 4).map(sug => (
                          <button
                            key={sug}
                            type="button"
                            onClick={() => setFormData({ ...formData, vibe: sug })}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all ${formData.vibe === sug
                              ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm'
                              : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                              }`}
                          >
                            + {sug}
                          </button>
                        ))}

                        {showMoreVibes && aiSuggestions.vibes.slice(4, 8).map(sug => (
                          <button
                            key={sug}
                            type="button"
                            onClick={() => setFormData({ ...formData, vibe: sug })}
                            className={`px-3 py-1.5 border rounded-full text-xs font-medium transition-all animate-in fade-in zoom-in-95 duration-200 ${formData.vibe === sug
                              ? 'bg-indigo-600 text-white border-indigo-600 shadow-sm'
                              : 'bg-white border-slate-200 hover:border-indigo-400 hover:bg-indigo-50 text-slate-600'
                              }`}
                          >
                            + {sug}
                          </button>
                        ))}
                      </div>

                      <button
                        type="button"
                        onClick={() => setShowMoreVibes(!showMoreVibes)}
                        className="flex items-center gap-1 text-xs font-bold text-indigo-600 hover:text-indigo-800 mt-2 transition-colors focus:outline-none"
                      >
                        {showMoreVibes ? (
                          <><ChevronUp className="w-3.5 h-3.5" /> Sembunyikan</>
                        ) : (
                          <><ChevronDown className="w-3.5 h-3.5" /> Rekomendasi lainnya</>
                        )}
                      </button>
                    </div>
                  </div>
                </div>

                <div className="space-y-6">
                  {/* Gaya Visual */}
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-3">Gaya Visual (Tampilan):</label>
                    <div className="grid grid-cols-2 gap-3">
                      {visualStyles.map((style) => (
                        <button
                          key={style.name}
                          type="button"
                          onClick={() => setFormData({ ...formData, visualStyle: style.name })}
                          className={`p-3 text-left rounded-xl border text-xs transition-all focus:outline-none ${formData.visualStyle === style.name
                            ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                            : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                            }`}
                        >
                          <div className="font-bold mb-1">{style.name}</div>
                          <div className="text-[10px] text-slate-500 leading-tight">{style.desc}</div>
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Hook Menarik */}
                  <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-bold text-slate-800 text-xs">Gunakan Hook Menarik</h4>
                        <p className="text-[10px] text-slate-500 max-w-[280px]">Membuat awal video memicu rasa ingin tahu audiens secara dramatis.</p>
                      </div>
                      <button
                        type="button"
                        onClick={() => setFormData({ ...formData, useHook: !formData.useHook })}
                        className="text-indigo-600 hover:scale-105 transition-transform focus:outline-none"
                      >
                        {formData.useHook ? (
                          <ToggleRight className="w-10 h-10 animate-in fade-in" />
                        ) : (
                          <ToggleLeft className="w-10 h-10 text-slate-400" />
                        )}
                      </button>
                    </div>
                    <div className="mt-3 bg-white px-3 py-2 rounded border border-slate-200/60 text-[10px] text-slate-600 italic">
                      {formData.useHook ? "Mulai dengan skenario emosional/pertanyaan pembuka" : "Mulai langsung membahas visual utama produk secara lugas"}
                    </div>
                  </div>
                </div>
              </div>

              {/* Gaya Voiceover */}
              <div className="mt-8 pt-6 border-t border-slate-100 grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="lg:col-span-2">
                  <label className="block text-sm font-bold text-slate-700 mb-3">Gaya Voiceover (Karakter & Tempo):</label>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {voiceStyles.map((voice) => (
                      <button
                        key={voice.name}
                        type="button"
                        onClick={() => setFormData({ ...formData, voiceStyle: voice.name })}
                        className={`p-3 text-left rounded-xl border text-xs transition-all focus:outline-none ${formData.voiceStyle === voice.name
                          ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                          : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                          }`}
                      >
                        <div className="font-bold mb-1 flex items-center gap-1 text-slate-800">
                          <Mic className="w-3.5 h-3.5 text-indigo-500" />
                          {voice.name}
                        </div>
                        <div className="text-[10px] text-slate-500 leading-tight">{voice.desc}</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Voiceover Language selection (Request 5) */}
                <div>
                  <label className="block text-sm font-bold text-slate-700 mb-3">Bahasa Voiceover:</label>
                  <div className="space-y-2.5">
                    {[
                      'Bahasa Indonesia',
                      'Bahasa Inggris',
                      'Bahasa Indonesia + Inggris (Gaul Jaksel)',
                      'Bahasa Jawa',
                      'Bahasa Sunda'
                    ].map(lang => (
                      <button
                        key={lang}
                        type="button"
                        onClick={() => setFormData({ ...formData, voiceLanguage: lang })}
                        className={`w-full p-3 text-left rounded-xl border text-xs font-semibold transition-all focus:outline-none flex items-center justify-between ${formData.voiceLanguage === lang
                          ? 'border-indigo-600 bg-indigo-50/50 text-indigo-900 ring-2 ring-indigo-500/20'
                          : 'border-slate-200 bg-white hover:bg-slate-50 text-slate-700'
                          }`}
                      >
                        <span>{lang}</span>
                        {formData.voiceLanguage === lang && <Check className="w-4 h-4 text-indigo-600" />}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex justify-between items-center mt-8 gap-4 flex-wrap">
                <button
                  onClick={handleBack}
                  disabled={isGenerating}
                  className="px-5 py-3 text-slate-600 font-bold hover:bg-slate-200 rounded-xl transition-colors text-sm"
                >
                  Kembali
                </button>
                <div className="flex items-center gap-3 ml-auto">
                  {generatedResults.length > 0 && (
                    <button
                      onClick={() => setStep(4)}
                      disabled={isGenerating}
                      className="px-5 py-3 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-xl transition-colors text-sm border border-slate-200"
                    >
                      Kembali ke Hasil Sebelumnya
                    </button>
                  )}
                  <button
                    onClick={generatePromptsWithGemini}
                    disabled={isGenerating || !formData.setting || !formData.vibe}
                    className="bg-indigo-600 text-white px-6 md:px-8 py-3 rounded-xl font-bold flex items-center gap-2 hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-200 text-sm disabled:opacity-50 disabled:shadow-none disabled:cursor-not-allowed"
                  >
                    {isGenerating ? (
                      <><Loader2 className="w-4 h-4 animate-spin" /> Menganalisis</>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4" />
                        {generatedResults.length > 0 ? "Buat Prompt Baru" : "Lanjut Buat Prompt"}
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* STEP 4: RESULTS */}
          {step === 4 && generatedResults.length > 0 && (
            <div className="flex flex-col md:flex-row min-h-[620px] animate-in fade-in slide-in-from-bottom-4 duration-300">

              {/* Sidebar Storyboard */}
              <div className="w-full md:w-1/3 border-r border-slate-200 bg-slate-50 p-4 md:p-6 flex flex-col justify-between">
                <div>
                  <h3 className="font-bold flex items-center gap-2 mb-2 text-slate-800 text-sm md:text-base">
                    <LayoutPanelLeft className="w-5 h-5 text-indigo-600" />
                    Storyboard
                  </h3>
                  <p className="text-[11px] text-slate-500 mb-4 pb-4 border-b border-slate-200 leading-relaxed">
                    Di bawah ini adalah Prompt Scene 1 s/d 5 yang dihasilkan secara berurutan oleh Gemini AI.
                  </p>

                  <div className="space-y-3 max-h-[360px] md:max-h-none overflow-y-auto pr-1">
                    {generatedResults.map((result, idx) => (
                      <button
                        key={idx}
                        onClick={() => {
                          setActiveTab(idx);
                          setCopiedStates({ image: false, video: false, voice: false });
                          // Scroll details into view on mobile
                          if (window.innerWidth < 768) {
                            document.getElementById('details-pane')?.scrollIntoView({ behavior: 'smooth' });
                          }
                        }}
                        className={`w-full text-left p-3 rounded-xl border transition-all duration-200 focus:outline-none ${activeTab === idx
                          ? 'bg-indigo-600 text-white border-indigo-700 shadow-md transform scale-[1.01]'
                          : 'bg-white border-slate-200 text-slate-700 hover:border-indigo-300'
                          }`}
                      >
                        <div className="flex justify-between items-center mb-1">
                          <span className={`text-[9px] font-extrabold px-1.5 py-0.5 rounded uppercase tracking-wider ${activeTab === idx ? 'bg-indigo-700 text-indigo-100' : 'bg-slate-100 text-slate-500'
                            }`}>
                            Scene {idx + 1}
                          </span>
                          {activeTab === idx && <CheckCircle className="w-3.5 h-3.5" />}
                        </div>
                        <h4 className="font-bold text-xs mb-1 line-clamp-1">{result.name.replace(/^\d+\.\s*/, '')}</h4>
                        <p className={`text-[11px] line-clamp-2 ${activeTab === idx ? 'text-indigo-100' : 'text-slate-500'}`}>
                          {result.description}
                        </p>
                      </button>
                    ))}
                  </div>
                </div>

                <div className="mt-6 pt-6 border-t border-slate-200 space-y-2">
                  <button
                    onClick={() => setStep(3)}
                    className="w-full py-2.5 flex items-center justify-center gap-2 text-xs font-bold text-indigo-600 bg-indigo-50 border border-indigo-100 rounded-xl hover:bg-indigo-100 transition-colors shadow-sm"
                  >
                    <ChevronLeft className="w-3.5 h-3.5" /> Sesuaikan Strategi
                  </button>
                  <button
                    onClick={handleReset}
                    className="w-full py-2.5 flex items-center justify-center gap-2 text-xs font-bold text-slate-600 bg-white border border-slate-300 rounded-xl hover:bg-slate-100 transition-colors shadow-sm"
                  >
                    <RefreshCcw className="w-3.5 h-3.5" /> Mulai Produk Baru
                  </button>
                </div>
              </div>

              {/* Main Prompt Display Area */}
              <div id="details-pane" className="w-full md:w-2/3 p-6 md:p-8 bg-white flex flex-col justify-between">
                <div>
                  {/* REVISI POIN 3: BADGES KONFIGURASI PILIHAN USER */}
                  <div className="mb-6 bg-slate-50 border border-slate-100 rounded-xl p-4 animate-in fade-in duration-300">
                    <span className="text-[10px] font-extrabold text-slate-500 uppercase tracking-widest block mb-2.5 flex items-center gap-1.5">
                      <Tag className="w-3 h-3 text-indigo-500" /> Ringkasan Konfigurasi
                    </span>
                    <div className="flex flex-wrap gap-2">
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        📦 {formData.category}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200" title={formData.productDetail}>
                        ✨ {formData.productDetail}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200" title={formData.setting}>
                        📍 Latar: {formData.setting}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200" title={formData.vibe}>
                        🎭 Vibe: {formData.vibe}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        👁️ Visual: {formData.visualStyle}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🎙️ Audio: {formData.voiceStyle}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🌐 Bahasa VO: {formData.voiceLanguage}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        👤 Gender Model: {formData.modelGender}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🪝 Hook: {formData.useHook ? 'Aktif' : 'Non-Aktif'}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        🖼️ Foto Produk: {productImages.length > 0 ? `Dilampirkan (${productImages.length} Foto)` : 'Tidak Ada'}
                      </span>
                      <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                        👩 Foto Model: {modelImages.length > 0 ? `Dilampirkan (${modelImages.length} Foto)` : 'Tidak Ada'}
                      </span>
                      {formData.usePlaceholder && (
                        <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                          👤 Tag Placeholder Karakter
                        </span>
                      )}
                      {formData.useProductPlaceholder && (
                        <span className="text-slate-700 bg-white shadow-xs px-2.5 py-1 rounded-lg text-[10px] font-semibold border border-slate-200">
                          📦 Tag Placeholder Produk
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b pb-4">
                    <div>
                      <span className="text-[10px] font-extrabold text-indigo-600 uppercase tracking-widest block mb-1">
                        {activeScene?.seq}
                      </span>
                      <h2 className="text-xl md:text-2xl font-black text-slate-800 mb-2">{activeScene?.name}</h2>
                    </div>
                  </div>

                  <div className="space-y-6">
                    {/* Image Prompt */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-indigo-700 font-bold text-sm">
                          <ImageIcon className="w-4 h-4" />
                          <span>Prompt Gambar</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a
                            href="https://www.midjourney.com"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-indigo-100 hover:bg-indigo-200 text-indigo-700 px-2 py-0.5 rounded font-bold transition-all border border-indigo-200 flex items-center gap-0.5"
                          >
                            Midjourney <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a
                            href="https://chat.openai.com"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-indigo-100 hover:bg-indigo-200 text-indigo-700 px-2 py-0.5 rounded font-bold transition-all border border-indigo-200 flex items-center gap-0.5"
                          >
                            DALL-E 3 <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea
                          readOnly
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-indigo-400 transition-colors leading-relaxed font-mono"
                          value={activeScene?.imagePrompt || ''}
                        />
                        <button
                          onClick={() => handleCopyText(activeScene?.imagePrompt || '', 'image')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${copiedStates.image
                            ? 'bg-green-600 text-white hover:bg-green-700'
                            : 'bg-indigo-50 hover:bg-indigo-100 text-indigo-600'
                            }`}
                        >
                          {copiedStates.image ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin</>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Video Prompt */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-blue-700 font-bold text-sm">
                          <Video className="w-4 h-4" />
                          <span>Prompt Video</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a
                            href="https://openai.com/sora"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Sora <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a
                            href="https://runwayml.com"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Runway <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a
                            href="https://klingai.com"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-blue-100 hover:bg-blue-200 text-blue-700 px-2 py-0.5 rounded font-bold transition-all border border-blue-200 flex items-center gap-0.5"
                          >
                            Kling AI <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea
                          readOnly
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-blue-400 transition-colors leading-relaxed font-mono"
                          value={activeScene?.videoPrompt || ''}
                        />
                        <button
                          onClick={() => handleCopyText(activeScene?.videoPrompt || '', 'video')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${copiedStates.video
                            ? 'bg-green-600 text-white hover:bg-green-700'
                            : 'bg-blue-50 hover:bg-blue-100 text-blue-600'
                            }`}
                        >
                          {copiedStates.video ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin</>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Voice Prompt & Script */}
                    <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 relative">
                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-3 border-b border-slate-200 pb-3">
                        <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm">
                          <Volume2 className="w-4 h-4" />
                          <span>Prompt Suara, Naskah & Panduan Audio</span>
                        </div>
                        <div className="flex flex-wrap items-center gap-1.5 text-[10px]">
                          <span className="text-slate-400 font-medium mr-1">Rekomendasi Tools:</span>
                          <a
                            href="https://elevenlabs.io"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-emerald-100 hover:bg-emerald-200 text-emerald-700 px-2 py-0.5 rounded font-bold transition-all border border-emerald-200 flex items-center gap-0.5"
                          >
                            ElevenLabs <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                          <a
                            href="https://lovo.ai"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="bg-emerald-100 hover:bg-emerald-200 text-emerald-700 px-2 py-0.5 rounded font-bold transition-all border border-emerald-200 flex items-center gap-0.5"
                          >
                            Lovo AI <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        </div>
                      </div>
                      <div className="relative">
                        <textarea
                          readOnly
                          className="w-full h-32 p-4 bg-white border border-slate-300 rounded-lg text-xs text-slate-700 resize-none focus:outline-none focus:border-emerald-400 transition-colors leading-relaxed"
                          value={activeScene?.voicePrompt || ''}
                        />
                        <button
                          onClick={() => handleCopyText(activeScene?.voicePrompt || '', 'voice')}
                          className={`absolute top-2 right-2 p-2 px-3 rounded-md text-xs font-bold transition-all shadow-sm flex items-center gap-1.5 ${copiedStates.voice
                            ? 'bg-green-600 text-white hover:bg-green-700'
                            : 'bg-emerald-50 hover:bg-emerald-100 text-emerald-600'
                            }`}
                        >
                          {copiedStates.voice ? (
                            <><Check className="w-3 h-3" /> Tersalin</>
                          ) : (
                            <><Copy className="w-3 h-3" /> Salin</>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-8 p-4 bg-amber-50 border border-amber-200 rounded-xl flex items-start gap-2.5 animate-pulse">
                  <span className="text-amber-500 font-bold text-xs shrink-0 mt-0.5">🎬 Tips Sinergi Storyboard:</span>
                  <p className="text-[11px] text-amber-800 leading-relaxed">
                    Setiap naskah scene di atas didesain **bersambung** membentuk jalan cerita iklan yang utuh. Bacakan atau buat audio secara berurutan (Scene 1 s/d Scene 5) untuk digabungkan menjadi satu video promosi utuh berdurasi 30 detik!
                  </p>
                </div>
              </div>

            </div>
          )}

        </div>
      </div>
    </div>
  );
}
